name: Sync changes to GitLab

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    if: (github.repository == 'adamlui/autoclear-chatgpt-history')
    runs-on: ubuntu-latest
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout adamlui/autoclear-chatgpt-history
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Push changes to gitlab.com/adamlui/autoclear-chatgpt-history
        run: |
          git push --force -o ci.skip \
            https://oauth2:${{ secrets.GITLAB_SYNC_PAT }}@gitlab.com/adamlui/autoclear-chatgpt-history.git main
